# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marcox_iter_ar1Cpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho) {
    .Call(`_marcox_marcox_iter_ar1Cpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho)
}

marcox_iter_excCpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho) {
    .Call(`_marcox_marcox_iter_excCpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho)
}

marcox_iter_indpCpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho) {
    .Call(`_marcox_marcox_iter_indpCpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho)
}

marcox_iter_kdCpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho, kv) {
    .Call(`_marcox_marcox_iter_kdCpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho, kv)
}

marcox_iter_toepCpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho) {
    .Call(`_marcox_marcox_iter_toepCpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho)
}

marcox_iter_unsCpp <- function(X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho) {
    .Call(`_marcox_marcox_iter_unsCpp`, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho)
}

matSolCpp <- function(mat, block, K, n, tol_cond = 1e3) {
    .Call(`_marcox_matSolCpp`, mat, block, K, n, tol_cond)
}

sandwich_ar1_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id) {
    .Call(`_marcox_sandwich_ar1_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id)
}

sandwich_exc_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id) {
    .Call(`_marcox_sandwich_exc_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id)
}

sandwich_indp_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id) {
    .Call(`_marcox_sandwich_indp_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id)
}

sandwich_kd_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id, kv) {
    .Call(`_marcox_sandwich_kd_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id, kv)
}

sandwich_toep_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id) {
    .Call(`_marcox_sandwich_toep_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id)
}

sandwich_uns_rcpp <- function(rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id) {
    .Call(`_marcox_sandwich_uns_rcpp`, rho, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id)
}

