# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marcox_iter_Cpp <- function(betainit_origin, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho, rho_vec_k, kv, rhomat, method) {
    .Call(`_marcox_marcox_iter_Cpp`, betainit_origin, X1, betainit, Lambda, c1, W1, id, new_uid, n, tol, maxIter, maxInner, pphi, rho, rho_vec_k, kv, rhomat, method)
}

matSolCpp <- function(mat, block, K, n, tol_cond = 1e3) {
    .Call(`_marcox_matSolCpp`, mat, block, K, n, tol_cond)
}

se_cpp <- function(clusteridx, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id, rhomat, Q1R, kv) {
    .Call(`_marcox_se_cpp`, clusteridx, betascale, betainit, gSS, kk, covnum, K, n, new_uid, xxx, c1, t2, tt1, gg1, Lambda, id, rhomat, Q1R, kv)
}

